---

# Docker repository branch
docker_repo: main
# docker_repo: testing
# docker_repo: experimental

# Extra packages that have to be installed together with Docker
docker_dependencies: "{{ default_docker_dependencies }}"

# Docker swarm network can be define in order to be sure that
# swarm cluster doesn't overlap with you infrastructure
docker_swarm_network: 10.10.8.0/24

# You can set any interface, that is listened by docker engine.
# e.g. docker_swarm_interface: "eth1"
docker_swarm_interface: "{{ ansible_default_ipv4['interface'] }}"
docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_' + docker_swarm_interface]['ipv4']['address'] }}"
docker_swarm_port: 2377

# Switches disabling the docker-engine, docker group and swarm-mode setup.
skip_engine: True # if true, skip the docker engine installation
skip_group: False # if true, does not add the docker_admin_users to the docker_group_name
skip_swarm: False  # if true, skip the swarm setup
skip_docker_py: False # if true, skip the docker-py
docker_stack_add_cleanjob: True # Kill dangling images on a timer.
docker_stack_auto_reload: True # Auto-reload new images from registry.

service_def_path: "api/prod.yml"

# Swarm labels

#pswarm_labels='["libvirt", "docker", "foo", "bar"]'
swarm_labels: '["registry_host=foo"]'

# Secure credential passthrough to encrypted vars file

prod_db_user: "{{ vault_prod_db_user }}"
prod_db_password: "{{ vault_prod_db_password }}"
prod_db_name: "{{ vault_prod_db_name }}"
prod_secret_key: "{{ vault_prod_secret_key }}"
sendgrid_api_key: "{{ vault_sendgrid_api_key }}"
