---

- name: Install docker python library
  pip:
    name: docker
    state: present
  become: yes

- name: Install docker python library - Python3
  pip:
    name: docker
    state: present
    executable: pip3
  become: yes
