---

- name: Install docker python library
  pip:
    name: docker
    state: present
  when: (ansible_version is not defined) or (ansible_version is defined
    and ansible_version.full | version_compare('2.2.0.0', '>='))
