---

# Variables setup
- name: Include os-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [stack-deploy]

- name: Include role variables.
  include_vars: ansible-dockerswarm.yml
  tags: [stack-deploy]

# Makes sure that the repo cache is fresh
- name: Update APT cache
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'
  changed_when: false
  become: yes

# Install the Docker Engine
- include: docker_engine.yml
  when: not skip_engine

# Setup the Docker Swarm Cluster
- include: swarm_cluster.yml
  tags: [swarm-deploy]

# Add secrets to swarm
- include: swarm-secrets.yml
  tags: [swarm-secrets]

# Deploy a Stack on the Docker Swarm Cluster
- include: swarm_stack.yml
  when: not skip_swarm and inventory_hostname == groups['docker_swarm_manager'][0]
  tags: [stack-deploy]
