---
# Configure docker-stack
- include_vars: ansible-dockerswarm_vars.yml
- include_vars: encrypted_vars.yml

- name: Add django secret key to swarm
  docker_secret:
    name: PROD_SECRET_KEY
    data: "{{ prod_secret_key }}"
    state: present
  when: "inventory_hostname == groups['docker_swarm_manager'][0]"

- name: Add db_user to swarm
  docker_secret:
    name: POSTGRES_USER
    data: "{{ prod_db_user }}"
    state: present
  when: "inventory_hostname == groups['docker_swarm_manager'][0]"

- name: Add db password to swarm
  docker_secret:
    name: POSTGRES_PASSWORD
    data: "{{ prod_db_password }}"
    state: present
  when: "inventory_hostname == groups['docker_swarm_manager'][0]"

- name: Add db name to swarm
  docker_secret:
    name: POSTGRES_DB
    data: "{{ prod_db_name }}"
    state: present
  when: "inventory_hostname == groups['docker_swarm_manager'][0]"

- name: Add django debug value to swarm
  docker_secret:
    name: DJANGO_DEBUG
    data: "False"
    state: present
  when: "inventory_hostname == groups['docker_swarm_manager'][0]"

- name: Add sendgrid API key to swarm.
  docker_secret:
    name: SENDGRID_API_KEY
    data: "{{ sendgrid_api_key }}"
    state: present
  when: "inventory_hostname == groups['docker_swarm_manager'][0]"
